# Generated by Django 5.1.3 on 2024-11-06 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('borrador', 'Borrador'), ('eliminado', 'Eliminado')], default='enviado', max_length=20)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to=settings.AUTH_USER_MODEL)),
                ('correos', models.ManyToManyField(blank=True, related_name='carpetas', to='emails.correo')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.FileField(upload_to='archivos/adjuntos/')),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='emails.correo')),
            ],
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_lectura', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('archivado', 'Archivado'), ('eliminado', 'Eliminado')], default='recibido', max_length=20)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='emails.correo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
