# Generated by Django 5.1.3 on 2024-11-06 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_remove_correo_estado_remove_destinatario_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='correo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios_correo', to='emails.correo'),
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos_destinatarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
