# Generated by Django 5.1.3 on 2024-11-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_correo_eliminado_por_remitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='eliminado_por_destinatario',
            field=models.BooleanField(default=False),
        ),
    ]
