# Generated by Django 5.1.3 on 2024-11-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_prioridad_correo_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
